# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
